### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by rodrigovedovato** [kahole/vscode-magit#1]
### Version
0.0.3

### Steps to reproduce
1. Open any folder on VS Code
2. Press `Ctrl+X G` to view `magit.status`

### Expected Behavior

Extension should be successfully activated and status should be shown

### What is happening

Extension fails to active with message:

```
Activating extension 'kahole.magit' failed: Cannot find module './rebasing/rebasingSectionView'
Require stack:
- /home/user/.vscode-insiders/extensions/kahole.magit-0.0.3/out/views/magitStatusView.js
- /home/user/.vscode-insiders/extensions/kahole.magit-0.0.3/out/commands/statusCommands.js
- /home/user/.vscode-insiders/extensions/kahole.magit-0.0.3/out/providers/contentProvider.js
- /home/user/.vscode-insiders/extensions/kahole.magit-0.0.3/out/extension.js
- /usr/share/code-insiders/resources/app/out/vs/loader.js
- /usr/share/code-insiders/resources/app/out/bootstrap-amd.js
- /usr/share/code-insiders/resources/app/out/bootstrap-fork.js.
```

**Comment by kahole** [comment]
Seems there was an issue with the naming of rebasingSectionView. It was upper case for some reason. Nothing else was.
Version 0.0.4 is published and addresses this
