### ISSUE TITLE
Support for interactive rebasing

### ISSUE THREAD

**Issue by zachdaniel** [kahole/vscode-magit#10]
This would be great also. I'm happy to contribute if you have any guidance on where to start.

**Comment by kahole** [comment]
My usual process is to see how far I can go with VSCode's built in features.
In the case of interactive rebase, I would try to do it similar to how I did commit message editing.

I mean
```bash
export GIT_EDITOR="code --wait"
git rebase -i master
```
is a running start.

**Comment by zachdaniel** [comment]
Thank you! 😇

**Comment by kahole** [comment]
Thank you for your feeback :)
Let me know if you have any more suggestions regarding this feature or something else.
