### ISSUE TITLE
Eliminate extra esc/enter press on switches

### ISSUE THREAD

**Issue by stevenguh** [kahole/vscode-magit#104]
I am not if this was discussed before. When switch menu is displayed, it doesn't exit on the correct switch click (it requires an extra esc/enter click).

I am wondering would you be open to eliminate that one extra click on correct switch selection. My reasons are as follow:
- We are already displaying all the "on" switches in the main menu, the information is still being display.
- A user can still reselect selection with by clicking `-` similar to magit
- The key press sequence would be similar to magit by eliminating that extra click, user will be able reuse their muscle memory
- Faster operation ;)

For example:
1. In the rebasing menu
2. Click `-` to enter switch menu
3. Click `i` to select interactive switch
4. Click `ESC` to exit to menu (Eliminate this step)
5. Click `e`

**Comment by kahole** [comment]
Thanks for the clear and concise presentation of this issue.

You're right about the keypress sequence and faster operation. However, I think the active switches indicator in the top level menu isn't nearly prominent/clear enough for this not to be extremely confusing (especially for non-emacs-users).

As long as the menu system is based on the quickPick hack, which probably already confuses new users, I'm of the opinion that some things are better off being different from the emacs magit menu system. This is a natural consequence of having much less screen real estate available for it.

**Comment by jtrakk** [comment]
I have this same issue. Coming from emacs, I have many years of "muscle memory" saying that I don't need to press enter there. I would like to have the option for experienced users to eliminate the extra keypress. How would you feel about an optional setting?

**Comment by stevenguh** [comment]
@kahole Would you open to a PR for adding the configuration so it can accommodate two types of users?

**Comment by kahole** [comment]
@stevenguh yes
