### ISSUE TITLE
Is it possible to push a commit rather than a branch?

### ISSUE THREAD

**Issue by joneshf-cn** [kahole/vscode-magit#105]
My current git workflow is to work primarily with commits (rather than branches). This works beautifully in `magit` proper, but I've been having some issues in `edamagit`. The main thing that's causing issues is that I'm not sure how to push a commit to a remote.

Is it possible to push a commit rather than a branch to a remote in `edamagit`? I know you can push a branch to a remote, but I can't seem to figure out how to do this when working directly with a commit. I'm looking for the equivalent of:
```Console
$ git push $REMOTE $COMMIT_SHA:refs/heads/$REMOTE_BRANCH_NAME
```

**Comment by kahole** [comment]
Do you use `P r explicit refspecs` for this in magit?

How do you enter the name of the remote branch you're pushing to?

**Comment by joneshf-cn** [comment]
Hmm. It's actually been a few months since I've used `magit` 😅, lemme try to remember/find a computer with emacs.

**Comment by joneshf-cn** [comment]
Looks like I used to do `P o $COMMIT_SHA $REMOTE/$REMOTE_BRANCH_NAME`. That looks like it's calling the `magit-push-other` function: https://magit.vc/manual/magit.html#Pushing.

What's helpful is that `magit` will suggest the current commit SHA for `$COMMIT_SHA`.

What's less helpful (in fact, primarily useless for this workflow) is that `magit` will suggest whatever the default remote is along with the current commit sha for the branch name. E.g. If I was pushing SHA `abcd1234` to the `origin` remote, it would suggest `abcd1234` for the `$COMMIT_SHA`, then `origin/abcd1234` for the `$REMOTE/$REMOTE_BRANCH_NAME`.

I don't need all of this behavior. I assume just getting the popup at the top with all the commits (like when using rebase in `edamagit`) would be enough for me.

**Comment by kahole** [comment]
This is increasingly becoming an issue for me as well. I don't maintain a functioning emacs config anymore, and that stuff rots. So opening emacs to try a quick thing in magit isn't always easy.
Maybe I should keep a vanilla + magit config around.

**Comment by kahole** [comment]
With v0.6.5 comes the "push another branch" command in which you can push any ref (freeform, but with branches suggested). You then input remote target branch which is also freeform with existing remote branches suggested.

**Comment by joneshf-cn** [comment]
Thanks for this! I'll try this out as soon as I can.

**Comment by joneshf-cn** [comment]
This works! Thanks again1
