### ISSUE TITLE
Opening and closing Magit can move you to another pane.

### ISSUE THREAD

**Issue by ilyagr** [kahole/vscode-magit#106]
## Bug description

When using VS Code with a window split in two panes, using Magit and quitting moves you to the other pane.

## To Reproduce

1. Open files in 2 panes in VS Code. Make sure you are in a git repository.
2. Press `Alt+x g q`, thus opening and closing Magit.

## Expected behavior
You are back in the same pane you started with.

## Actual result
You are in the opposite pane, not the one you started with.

## Additional context

I also filed this as https://github.com/VSpaceCode/VSpaceCode/issues/174, but I think it has nothing to do with VSpaceCode, actually.

This becomes especially annoying if you also open a help window. See https://github.com/VSpaceCode/VSpaceCode/issues/173 for the way it got me confused.

**Comment by kahole** [comment]
This has to do with how VSCode behaves when exiting windows. I feel its better to stick to the native VSCode window behaviour in this situation. This will surely rabbit-hole if not.
The goal of this project is not to emulate emacs magit, but provide a magit-like extension for VSCode, where VSCode should be utilized for its strengths, but the extension should also be idiomatic and symbiotic with the rest of VSCode and the extension ecosystem. (In my view, this is where the VSCodeVim extension went wrong)

**Comment by ilyagr** [comment]
Thanks for looking into it. https://github.com/kahole/edamagit/commit/11dd43885b89fbb728072751d8b1a67f1879d6fb should also help.

**Comment by fiveNinePlusR** [comment]
for me it's less of an issue of having it be consistent with magit and more so it makes sense on how it works... it's pretty jarring to have the focus not be where you expect it to be.
