### ISSUE TITLE
some default shortcuts act wrong (Vim)

### ISSUE THREAD

**Issue by lyjdwh** [kahole/vscode-magit#11]
**Vscode version**: 1.43.0
**linux**: manjaro kde

1. some default shortcuts like ctrl+x g, ctrl+x alt+g, ctrl+x ctrl+g, tab are not responding! I have to add them to my user keybindings to make it work.
2. `    {
        "key": "q",
        "command": "workbench.action.closeActiveEditor",
        "when": "editorTextFocus && editorLangId == 'magit'"
    },` The `editorLangId == 'magit'"` doesn't seem to work, as the shortcut 'q' work everywhere!
 
I don't konw how to fix the second one, every time I press 'q', it will close one file buffer!

**Comment by kahole** [comment]
Do you have any other extensions installed that might interfere?

**Comment by kahole** [comment]
@lyjdwh
A temporary fix for 2. is to find the shortcut in Keyboard Shortcuts and delete it.
Search for 'closeActiveEditor'

Or just adding this to your keybindings settings file
```
  {
    "key": "q",
    "command": "-workbench.action.closeActiveEditor",
    "when": "editorTextFocus && editorLangId == 'magit'"
  }
```

**Comment by kahole** [comment]
As an experiment, after removing the 'q' keybinding above.
Try adding in these one at a time and see if `shift+q` works like expected, and if `q` in user settings doesn't. 
```
    {
      "key": "shift+q",
      "command": "workbench.action.closeActiveEditor",
      "when": "editorTextFocus && editorLangId == 'magit'"
    },
```
I think single key keybindings are broken on some systems likely due to an bug in VSCode:
```
    {
      "key": "q",
      "command": "workbench.action.closeActiveEditor",
      "when": "editorTextFocus && editorLangId == 'magit'"
    },
```

**Comment by lyjdwh** [comment]
Just as you say ,shift+q never gets invoked, and if q does.When I update magit to 0.11, it works.
Thanks very much!
But another problem that the vim extention 's recording macro which is binded on 'q' doesn't work.
The extension vscode-dired also has a 'q' keybind, but it doesn't influence the vim.

`{
  "key": "q", 
  "command": "extension.dired.close",
  "when": "dired.open && !findWidgetVisible && !inQuickOpen"
}`

**Comment by kahole** [comment]
> some default shortcuts like ctrl+x g, ctrl+x alt+g, ctrl+x ctrl+g, tab are not responding! I have to add them to my user keybindings to make it work.

I think the explanation  here is that there are contending keybindings between the extensions,
but user defined keybindings override all extensions.
VSCodeVim has really 'global' keybindings.
I've added a section in README for Vim support: [kahole/vscode-magit#vim-support-vscodevim](https://github.com/kahole/vscode-magit#vim-support-vscodevim)

> But another problem that the vim extention 's recording macro which is binded on 'q' doesn't work.

When it comes to 'q', Vim hasn't defined a keybinding for it. I'm not sure how they listen to key events.
I'm not able to reproduce this issue either, so not sure how to proceed.
VSCodeVim does affect a lot of things

**Comment by pushqrdx** [comment]
@kahole they don't define it in `package.json` but instead hijack all typing events with this, it's pretty necessary for vim plugins to do so so that they handle modes and complex motions correctly

```js
 commands.registerCommand('type', (args) => { ... })
```

**Comment by lyjdwh** [comment]
It all make sense! Thanks very much!

**Comment by kahole** [comment]
@lyjdwh @pushqrdx if either of you are still experiencing issues with VSCodeVim compatibility feel free to open up a new issue specifically about this.
