### ISSUE TITLE
Add Instant Fixups

### ISSUE THREAD

**Issue by nathantalewis** [kahole/vscode-magit#110]
From the [docs](https://magit.vc/manual/magit/Initiating-a-Commit.html):
`c F (magit-commit-instant-fixup)`

The same functionality can be achieved today by first doing a normal fixup commit `c f`, then running an interactive rebase with the autosquash and autostash flags `r -a -A -i i`. However, the instant fixup is a nice-to-have that saves a few steps every time I want to tweak something from a previous commit.

**Comment by kahole** [comment]
#### Version [0.6.6]
- Adds 'instant fixup' command (#110)
