### ISSUE TITLE
Visual indication of branches and tags

### ISSUE THREAD

**Issue by troglotit** [kahole/vscode-magit#113]
Because branches names and tags are not visually emphasized, it's a bit harder than original Magit. It's not *high priority* or anything, just nice-to-have. 

Magit and Edamagit screenshots of same repo: 

![image](https://user-images.githubusercontent.com/10955264/111119917-c35c2680-857b-11eb-8523-4179dcd2d43a.png)
![image](https://user-images.githubusercontent.com/10955264/111119937-cb1bcb00-857b-11eb-94e2-5d83294f93a5.png)

**Comment by kahole** [comment]
They are highlighted when using the default vscode theme, as well as many other themes.

I am open for adding/changing the grammar scopes if any good suggestions/replacements are presented.

You can also customize the theme you are using as a last ditch solution:

https://medium.com/@nuozheng/how-to-customize-visual-studio-code-theme-colors-a6fb1e94f71f

**Comment by troglotit** [comment]
Oh, thank you, my bad, looks awesome in other themes!

**Comment by shelper** [comment]
@troglotit could you share which token exactly to customize this thing?

**Comment by troglotit** [comment]
@shelper I haven't ever customized tokens in a theme, and currently I use neovim, but maybe you could look into https://github.com/kahole/edamagit/blob/develop/syntaxes/magit.tmGrammar.json
