### ISSUE TITLE
Clarify which files are selected in status

### ISSUE THREAD

**Issue by jtrakk** [kahole/vscode-magit#115]
In Emacs Magit, when I run magit-status and select the first two files, they are both highlighted

![image](https://user-images.githubusercontent.com/43392409/112053131-341db880-8b11-11eb-9c2b-9f51e4226cac.png)

so that when I press kill, it's clear that I'm going to delete both files. 

In edamagit, the same action only shows one file highlighted,

![image](https://user-images.githubusercontent.com/43392409/112053143-3b44c680-8b11-11eb-905f-dd520808e133.png)

even though two are actually selected. I tried to kill one file, but accidentally deleted another untracked file, because the other one didn't look like it was selected, so I lost that file.

**Comment by kahole** [comment]
It was under your cursor though.
What's under the cursor is usually the thing thats affected.

However, I can understand the confusion with the highlight, and frustration with losing a file.

I will try and think if there is some way to improve upon this.

Thanks for reporting.

**Comment by kahole** [comment]
I did some work in the branch [feature/strongerDiffHighlighting](feature/strongerDiffHighlighting) using a custom highligh implementation to make it highlight more like emacs-magit. However, it is to brittle to be used.
Sadly the APIs are a bit limited in this area.

**Comment by jtrakk** [comment]
Fwiw it actually does give a confirmation prompt for each file, but in the real example I had like 6 files selected so I just spammed `y` without checking each filename individually.

**Comment by kahole** [comment]
That's a good point, it should be changed to only 1 confirm dialog listing all the files.
That needs to be fixed.

**Comment by jtrakk** [comment]
I think that's a separate issue: https://github.com/kahole/edamagit/issues/129

**Comment by jtrakk** [comment]
What was the resolution? I don't see anything different on v0.6.13.

**Comment by kahole** [comment]
No clear issue in context of edamagit's current selection highlighting. It is in line with other stuff in vscode.

As explained earlier strong diff and selection highlighting is worked on. In that context this is a non-issue, but I'm basically stuck, since the decoration APIs give a jittery/blinking render of the UI. And that's why I'm closing it, it doesnt add anything of value in the list of issues.

**Comment by jtrakk** [comment]
Ok I understand. Thanks for trying.
