### ISSUE TITLE
Add settings to control status view sections

### ISSUE THREAD

**Issue by dandavison** [kahole/vscode-magit#120]
I would like to be able to exclude certain sections from the status view (for example, personally I usually only want to see untracked, unstaged and staged, i.e. don't want to see stashes, unmerged, unpulled, unpushed, recent commits).

In magit this is done with something like

```emacs-lisp
(setq magit-status-sections-hook
      '(magit-insert-merge-log
        magit-insert-rebase-sequence
        magit-insert-am-sequence
        magit-insert-sequencer-sequence
        magit-insert-bisect-output
        magit-insert-bisect-rest
        magit-insert-bisect-log
        magit-insert-untracked-files
        magit-insert-unstaged-changes
        magit-insert-staged-changes))
```

https://magit.vc/manual/magit.html#Status-Sections
https://magit.vc/manual/magit.html#Section-Hooks

If you're in favour, do you have a view yet on what the settings interface should be? For example, perhaps something like this, i.e. an array of strings, trying to stay close to the magit section-hook names where there is a direct correspondence?

```json
  "magit.statusSections" : [
    "untracked",
    "unstaged",
    "staged"
  ]
```

**Comment by kahole** [comment]
Interesting. I'll see if I'm able figure out something nice.
The customizability and extensibility of emacs/elisp/magit are somewhat difficult to replicate in VSCode.

**Comment by dandavison** [comment]
Great. I'd be happy to submit a PR once the settings interface is decided if that helps at all (it might be a trivial PR at that point so may only help me learn extension development).

**Comment by kahole** [comment]
I would like it to be the inverse setting.
So something like this:
```
  "magit.hideStatusSections" : [
    "stashes",
    "unpulled",
    "unpushed",
    "recent commits"
  ]
```

It should be "parsed" in `loadConfig()` so `magitStatusView.ts` can easily just check some bools or similar.

One thing to watch out for is the logic for unpulled / unpushed / recent commits. These will show up and hide based on the presence of eachother.

Let me know if anything's unclear. :)

**Comment by dandavison** [comment]
Great, I'll follow that and make you a PR.
