### ISSUE TITLE
discard-at-point should discard unstaged only

### ISSUE THREAD

**Issue by dandavison** [kahole/vscode-magit#130]
**To reproduce:**

1. Add a chunk of consecutive lines to a file 
2. Issue `magit.status`
3. Stage some of the lines
   <table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/116742906-18d28280-a9c6-11eb-9ea1-6a343638890c.png" alt="image" /></td></tr></table> 
 
4. Now place the cursor on the `modified` file line in the _Unstaged_ section and press `k` (`magit.discard-at-point`). You will see the pink message in the screenshot below (note: the cursor must be on the file line, not within the hunk. The bug does not occur if the message says "discard hunk")
  <table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/116743067-5b945a80-a9c6-11eb-99aa-7c99173d0fd1.png" alt="image" /></td></tr></table>
  
5. Enter `y` to confirm.

**What should happen:**
The unstaged changes should be removed, and the staged changes should remain.

**What does happen:**
Both staged and unstaged changes are removed.
  <table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/116743277-b62db680-a9c6-11eb-9a75-ecaedfb4296f.png" alt="image" /></td></tr></table>

**Comment by lisp719** [comment]
I think it's because HEAD is specified in checkout.

https://github.com/kahole/edamagit/blob/develop/src/commands/discardAtPointCommands.ts#L55

**Comment by kahole** [comment]
Fix released in v0.6.16
