### ISSUE TITLE
Why is annotate not available when tagging?

### ISSUE THREAD

**Issue by andrewtimberlake** [kahole/vscode-magit#136]
I see the flag is commented out at https://github.com/kahole/edamagit/blob/develop/src/commands/taggingCommands.ts#L19

I’m happy to help with the implementation if you can point me in the right direction.

**Comment by kahole** [comment]
No particular reason, just haven't gotten to it.

The annotated tag requires a message input. So either through an input box, or through invoking the "interactive editor", like a commit message. I don't know how emacs-magit does it.
Input box is probably the best for this.

Look at `taggingCommands.ts -> createTag()` for inspiration
Something like...
```
const message = await window.showInputBox({ prompt: `Annotate '${tag}' with message:` });
```
