### ISSUE TITLE
Change default keybindings to avoid hijacking CTRL-X for cut

### ISSUE THREAD

**Issue by bmartin** [kahole/vscode-magit#14]
I've moved from Emacs to VSCode and the biggest thing I'm missing is Magit and this looks super promising so far. Big stumbling block with CTRL-x, though. Is there a way to make this work without overriding that key?

**Comment by kahole** [comment]
It might not be the best default, yeah.

Adding this to your VSCode [keybindings.json](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization) should do it:

```json
  // Remove default bindings:
  {
    "key": "ctrl+x g",
    "command": "-magit.status"
  },
  {
    "key": "ctrl+x alt+g",
    "command": "-magit.dispatch"
  },
  {
    "key": "ctrl+x ctrl+g",
    "command": "-magit.file-popup"
  },
  // Add your own:
  {
    "key": "ctrl+m m",
    "command": "magit.status"
  },
  {
    "key": "ctrl+m alt+m",
    "command": "magit.dispatch"
  },
  {
    "key": "ctrl+m ctrl+m",
    "command": "magit.file-popup"
  }
```

**Comment by kahole** [comment]
Also, see issue #7

**Comment by bmartin** [comment]
I'll use the keybindings, but please consider changing the defaults. I really hope you succeed in offering this awesome plugin to many VSCode users and I think CTRL-X will be a big blocker on wide adoption.

**Comment by kahole** [comment]
Agreed, I've now changed them to use `alt` instead of `ctrl`.
