### ISSUE TITLE
Existing lockfile error during commit doesn't get displayed

### ISSUE THREAD

**Issue by The-Compiler** [kahole/vscode-magit#144]
With VS Code 1.56.2 and Edamagit 0.6.13, I was trying to commit in a repository while a commit editor was already open elsewhere. Trying to commit on the command-line results in:

```
$ git commit
fatal: Unable to create '/home/florian/proj/qutebrowser/git/.git/index.lock': File exists.

[...]
```

but when commiting with edamagit, `staged.magit` gets opened and immediately closed again. However, the `status.magit` buffer doesn't show any error (like it does when other git commands failed).

**Comment by kahole** [comment]
What does the edamagit process log say?
Pressing '$' from the status view.

**Comment by The-Compiler** [comment]
```
[128] git commit --all
fatal: Unable to create '/home/florian/proj/qutebrowser/git/.git/index.lock': File exists.

[...]
```

![image](https://user-images.githubusercontent.com/625793/120286384-79532900-c2be-11eb-841b-7807ec30d2fb.png)

**Comment by kahole** [comment]
This has been fixed  in 4727ac988aa6d37b21f5ee82b40a2ff0d4ece1f7
Will be part of next release

**Comment by kahole** [comment]
v0.6.15 released now

**Comment by The-Compiler** [comment]
Thanks, seems to work great! :+1:
