### ISSUE TITLE
Reword no longer works (unless you have staged changes)

### ISSUE THREAD

**Issue by glasser** [kahole/vscode-magit#145]
[This commit](https://github.com/kahole/edamagit/commit/ddd27d8bacfaafba64b0b59e13c83540239c25df) changes the experience of using reword (`cw`) so that you get unnecessarily asked whether you want to stage changes first if there are no staged changes.

If you say no, the command ends.
If you say yes, git has an (invisible) error noting that you can't combine `--all` with `--only`.
So either way the reword fails.

You can work around it by staging an unrelated change :)

**Comment by kahole** [comment]
Good find, cheers 👍 Fixed in v0.6.14
