### ISSUE TITLE
Link to website broken

### ISSUE THREAD

**Issue by jacobemcken** [kahole/vscode-magit#147]
The link "Tutorial" from the extension page is dead (gives a 404 - not found)
![edamagit](https://user-images.githubusercontent.com/1869708/121197034-420dea80-c871-11eb-9e94-61c68bbfc582.png)

URL: https://hole.dev/articles/edamagit-introduction/

**Comment by kahole** [comment]
Sorry about that,
you can read the archived version here while I get it fixed: https://web.archive.org/web/20210414092244/https://hole.dev/articles/edamagit-introduction/

Thanks for letting me know! :)

**Comment by kahole** [comment]
Back up now: https://hole.dev/articles/edamagit-introduction/
