### ISSUE TITLE
Enable in untrusted workspaces?

### ISSUE THREAD

**Issue by The-Compiler** [kahole/vscode-magit#154]
With VS Code 1.57, [Workspace Trust](https://code.visualstudio.com/docs/editor/workspace-trust) was introduced.

edamagit doesn't seem to declare support for running on untrusted workspaces, so it gets disabled when opening an untrusted folder.

I'm wondering if it'd be safe to enable edamagit no matter what the workspace contents are? I'm guessing running git on untrusted projects should be fine, but not sure what else edamagit is doing exactly. See https://github.com/microsoft/vscode/issues/120251 for some more context.

As a workaround, doing

```json
    "extensions.supportUntrustedWorkspaces": {
        "kahole.magit": { "supported": true },
    },
```

in `settings.json` should enable the extension again, though I haven't actually tested (as I'm not sure if it should be running in untrusted workspaces really).

**Comment by kahole** [comment]
I'm not all that familiar with this concept yet. But running edamagit is not that different from running git. For the most part, it runs git commands underneath.

**Comment by kahole** [comment]
v0.6.17 has support for untrusted workspaces. Thanks for reporting this
