### ISSUE TITLE
Add keystroke for expanding all diffs in section

### ISSUE THREAD

**Issue by bmartin** [kahole/vscode-magit#155]
Magit has a bunch of options for controlling which status sections are open:

https://magit.vc/manual/magit.html#Section-Visibility-1

I believe many of these are inherited from org-mode and are a bit overkill.

What I do frequently wish for is "expand all staged diffs" and "collapse all staged diffs".

For example, it would be good to, move cursor to the top of "Unstaged" section and press "ctrl-tab" to fully expand the diffs. Then I can use "ctrl-f" to find the one changing some function I care about.

**Comment by kahole** [comment]
Added command for this now in 0.6.17.
`magit.toggle-all-folds-in-change-section-at-point`

You need to add the keybinding yourself though. As ctrl+tab is a frequently used keybinding for switching tabs in vscode.
Add to keybindings.json:
```
  {
    "command": "magit.toggle-all-folds-in-change-section-at-point",
    "key": "ctrl+tab",
    "when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
  },
  ```

**Comment by bmartin** [comment]
Good point about ctrl+tab. I think shift-tab should be available.
