### ISSUE TITLE
Pressing enter inside a modified chunk doesn't open the edited file in the right location

### ISSUE THREAD

**Issue by marjakh** [kahole/vscode-magit#16]
Steps to repro:

Edit a file (e.g., add a line)
Open magit status
Expand the changes with tab
Move the cursor e.g., to an added line
Press Enter

Expected: it opens the edited file, in the right location, where the change is. (This is how the original magit works.)

Actual: it opens the edited file but at the top (need to search for the changed location manually).

**Comment by kahole** [comment]
I've addressed this in v0.1.4 which was just released. Let me if this solves the issue
