### ISSUE TITLE
Staging chunks of file

### ISSUE THREAD

**Issue by leighmcculloch** [kahole/vscode-magit#162]
Edamagit is great, one thing I've noticed missing is the ability to stage parts/chunks of a file without staging the entire file. One of the selling points of magit is that it makes this trivial.

It's possible the feature is here and I've just missed it.

**Comment by kahole** [comment]
It is already here. Just visually select the stuff you want to stage and press 's'.
Same for unstage and discard.

**Comment by leighmcculloch** [comment]
Thanks @kahole. I must have something configured not quite right. I'm using the keybindings from the readme for VIM.

When I view the status page, and view the diff for a file, I can't stage parts of the diff. Using `s` on the diff doesn't do anything.

I'm positive I'm doing something silly. Any tips?

**Comment by kahole** [comment]
I think perhaps VSCodeVim's selection doesn't work for this, since they use a non-native selection which no other extensions are aware of.
Try native selection and let me know. (Eithet by deactivating vim or by using mouse/native selection keys)

**Comment by accoumar12** [comment]
> It is already here. Just visually select the stuff you want to stage and press 's'.
Same for unstage and discard.

This is not working either for me. I am using also vim for Vscode. I tried to disable it but it did not work either.

Instead, I am using the "Git: Stage Selected Range", which works really well!
