### ISSUE TITLE
Please support opening folders in magit status. 

### ISSUE THREAD

**Issue by fxdave** [kahole/vscode-magit#165]
I was trying to check the untracked files but when I move my cursor to a directory and I press enter, it tries to open the folder as a file that does not exist. 

Example:

**Untracked files (3)**
src/pages/Viewports/
src/services/
src/ui/TextEditor/

**Comment by kahole** [comment]
Fixed!

**Comment by kahole** [comment]
Thanks for reporting 👍

**Comment by fxdave** [comment]
Cool thanks!

**Comment by kahole** [comment]
Version 0.6.20 is released with the fix
