### ISSUE TITLE
no rendered colors at all

### ISSUE THREAD

**Issue by frodo4fingers** [kahole/vscode-magit#170]
hi @kahole 

specs: manjaro linux and VSCodium/VSCode (1.59.0)

first of all: i love working with edamagit - it makes my git workflow much more faster!
but on my private laptop i encounter an issue with the to-be-rendered colors:
```
Staged changes (1)
new file   settings.yaml
@@ -0,0 +1 @@[m
[32m+[m[32mcsv_directory: /home/me/Downloads/giro[m
```

any idea where this comes from?

**Comment by kahole** [comment]
Probably the git colo.ui setting.

Try setting it to auto

```
git config --global color.ui auto
```

> The auto part says that git will only try and use color on terminals that support it, and you will not get ANSI sequences if you redirect output of git commands to a file for example. Setting it to true is same as auto, and this is also the default since Git 1.8.4.

(https://unix.stackexchange.com/questions/44266/how-to-colorize-output-of-git)

**Comment by frodo4fingers** [comment]
this totally did the trick, thanks!
