### ISSUE TITLE
Push / Set Upstream Often Fails: could not lock config file .git/config: File exists

### ISSUE THREAD

**Issue by jeremyjh** [kahole/vscode-magit#182]
Usually I cannot set the upstream branch in edamagit because I get this error: `error: could not lock config file .git/config: File exists`.

In the longer log, I can see that the first operation succeeds, and the second fails. I believe this is because the first operation has not always completed yet when the second operation begins.
```
[0] git config --local branch.trya-commit.merge refs/heads/trya-commit
[255] git config --local branch.trya-commit.remote origin
error: could not lock config file .git/config: File exists
```

The reason is here:
https://github.com/kahole/edamagit/blob/5af1aa36ee6fdd1a5c8f8034a2527dd27b5e6278/src/commands/pushingCommands.ts#L119

Git's config file is not a database that can be accessed by multiple processes simultaneously. Those operations should not be attempted in parallel.

**Comment by kahole** [comment]
Feel free to submit a PR
