### ISSUE TITLE
Unable to checkout a single commit 

### ISSUE THREAD

**Issue by hikrr** [kahole/vscode-magit#188]
Steps to reproduce:

- go to the magit status view
- `l l` to go to the log
- move cursor on the commit to be selected and checked out (past commits)
- press`ENTER` will show the detail of the commit
- `bb` => only showing branches and press `ENTER` again cannot switch to the commit, can only checkout the last commit of a branch

Is that normal or did I miss any steps?
Thanks for the effort!

**Comment by kahole** [comment]
In the last step there you can enter any ref (commit short hash, branch name, etc) and press enter to checkout.
The branches are only there as suggestions.

Copy and paste short hash works pretty well
