### ISSUE TITLE
[Feature] Add -prune switch to pull command (F)

### ISSUE THREAD

**Issue by MarcoBuess** [kahole/vscode-magit#192]
See the description. It would be really convenient, to add  `--prune` switch to the pull command. This eliminates the need to run `fetch --prune` before running `pull`.

**Comment by kahole** [comment]
Added in v0.6.26

**Comment by MarcoBuess** [comment]
Prune switch doesn't remove remote branches that are deleted. They will still only be removed by using `fetch` with `--prune`. It logs `[0] git pull --prune origin master` but doesn't remove the non existent remotes.
