### ISSUE TITLE
Extension breaks when VS Code Insiders Edition is updated

### ISSUE THREAD

**Issue by nikoheikkila** [kahole/vscode-magit#194]
Hi,

When the VS Code Insiders Edition receives a new update (typically many times a week), and I reload the IDE, the extension cannot find the `code --wait` command anymore and thus errors when entering the commit message window. After updating, I can fix this manually by symlinking the `code-insiders` to `code` in my `PATH`.

I suppose there might be a hard-coded path somewhere that breaks? Using this in WSL Ubuntu 20.04 under Windows 11.

**Comment by kahole** [comment]
Is this still happening?
