### ISSUE TITLE
Can't commit inside a flatpak

### ISSUE THREAD

**Issue by daniellandau** [kahole/vscode-magit#199]
Previous issues on the same problem in different situations:

https://github.com/kahole/edamagit/issues/108
https://github.com/kahole/edamagit/issues/73
https://github.com/kahole/edamagit/issues/49
https://github.com/kahole/edamagit/issues/25

In my case I'm using https://flathub.org/apps/details/com.visualstudio.code-oss (repository at https://github.com/flathub/com.visualstudio.code-oss/) and the executable path is `/app/bin/code-oss`. It's not the only flatpak vscode though, so others might behave differently. How about allowing the user to optionally give the path explicitly to account for all the ways people might have vscode installed?

**Comment by kahole** [comment]
You can explictely set the path to your code instance in edamagit settings here:

<img width="769" alt="Screenshot 2022-02-21 at 12 35 40" src="https://user-images.githubusercontent.com/9072087/154947760-684e6236-1bd6-4316-97d8-887fc3cc96f1.png">
