### ISSUE TITLE
Command "Magit Status" caused (Failed to execute git)

### ISSUE THREAD

**Issue by TTTPOB** [kahole/vscode-magit#203]
sorry for the chn interface
![image](https://user-images.githubusercontent.com/19909103/154435461-414654f8-463f-4cd5-8e44-89594614f6af.png)
it means `command Magit Status caused (Failed to execute git)`
this vscode is running in vscode-remote, the remote server is a linux server
I can run git commands in linux shell smoothly as well as vscode native git interface
I don't know how to locate the bug, like where I can see the log output?

this problem is not happening all the time, but it happens most of the time, like, 9 out of ten

It starts just about 1week ago, But I've not done anything related to vscode or git after that, I've looked into the release history of this plugin, the latest update happens before that, I have no idea what is happening

**Comment by TTTPOB** [comment]
hmmm, disappeared magically after server reboot

**Comment by TTTPOB** [comment]
no, false negative, the problem remains
what can i do to locate the problem?

**Comment by kahole** [comment]
Try to access the log of the extension host. Not sure how you do that for remote vscode

**Comment by TTTPOB** [comment]
> Try to access the log of the extension host. Not sure how you do that for remote vscode

thank you, i've found the problem is related to an git diff extension nbdime
