### ISSUE TITLE
`gg` on status buffer should bring to top

### ISSUE THREAD

**Issue by alk-mandrianarijaona** [kahole/vscode-magit#206]
Unlike other file buffers, using `gg` on the git status buffer does not bring the cursor to top. In Magit, this works as expected.

**Comment by kahole** [comment]
Here's how to make `g g` from VSCodeVim work with edamagit: https://github.com/kahole/edamagit#vim-support-vscodevim

--

In emacs magit `g` refreshes the status buffer, just like in edamagit. The cursor happens to be reset at the top, but only after a full refresh. This is not a navigational command, and I think the behaviour of keeping the cursor in position is better.

`gg` is vim shortcut for going to the top of a file, maybe your confusing them if you are using som vim emulation together with magit/edamagit. At the top of this reply is a link to the readme-section describing how to make the `g g` binding from another package work with edamagit.

**Comment by alk-mandrianarijaona** [comment]
Thanks for that
