### ISSUE TITLE
Stash Options are Opposite of Magit

### ISSUE THREAD

**Issue by jeremyjh** [kahole/vscode-magit#208]
The `i` and `w` options in the stash submenu work exactly the opposite of how they do in Emacs magit. Is this intended? In magit, `w` STASHES the worktree, meaning it stashes whatever has not been staged. In edamagit, `w` SAVES the worktree, meaning it stashes what has been staged. 

Is this intended? It is very confusing and for quite awhile I thought these options were simply broken.

**Comment by kahole** [comment]
Yeah, no, it's definitely wrong in edamagit.
Confusing language from magit though imo 😆 .. but I guess we're "saving" the worktree from being stashed.

**Comment by pbiggar** [comment]
Hi, this seems to still be happening in the latest version. I'm using 0.6.29 and when I choose `w`, it stashes the Staged files.
