### ISSUE TITLE
Open Magit on a new tab page instead of split screen

### ISSUE THREAD

**Issue by Leiyi548** [kahole/vscode-magit#221]
First of all, thank you very much for your extension, which allows me to experience Magit in vscode. I want to know if I can open Magit in a new tab page instead of split screen. I didn't find this option in the settings.

**Comment by kahole** [comment]
Setting this to `same-column` should open magit buffers in a new tab instead of splitting the screen:

<img width="598" alt="Screenshot 2022-09-03 at 11 29 47" src="https://user-images.githubusercontent.com/9072087/188264767-385d409b-f3d0-4916-8d12-7f51fc51bfc2.png">
