### ISSUE TITLE
Installing Github Pull Request makes edamagit command fails

### ISSUE THREAD

**Issue by azzamsa** [kahole/vscode-magit#222]
After installing [microsoft/vscode-pull-request-github: GitHub Pull Requests for Visual Studio Code](https://github.com/Microsoft/vscode-pull-request-github). The edamagit command will fails. Saying "command not found".

Disabling Github Pull Request solves the issue.

**Comment by kahole** [comment]
Not able to reproduce. Perhaps `vscode-pull-request-github` as updated and become a better fellow citizen.
Do you still experience this issue?

**Comment by azzamsa** [comment]
I disabled `vscode-pull-request-github` and use Edamagit happily ever after.
