### ISSUE TITLE
Feature request: Make `Alt-x` magit prefix a setting

### ISSUE THREAD

**Issue by aguynamedben** [kahole/vscode-magit#224]
Hi, thank you for making this. I love it so much.

For many years I've used macOS + Emacs + magit and had my magit prefix set to `C-x`, i.e. `C-x g`
<img width="186" alt="image" src="https://user-images.githubusercontent.com/107841/193705413-3de2d7a4-2761-4c96-abea-28c56f978d02.png">

Is there a way to easily change the prefix from `Alt-x` to something else? As a reference, the Awesome Emacs Keymap has a setting that allows Mac users to use "Cmd as Meta".
```js
  ////////////////////////////////////
  // Awesome Emacs Keymap extension //
  ////////////////////////////////////
  // https://marketplace.visualstudio.com/items?itemName=tuttieee.emacs-mcx
  // Use Cmd as Meta key
  "emacs-mcx.useMetaPrefixMacCmd": true,
```

I was wondering if it's every been considered for this project. I know I can go in and override in each case it in Keyboard Shortcuts, just wondering if there's a way to do it with a single setting.

Thank you so much for making this!

**Comment by kahole** [comment]
Here's all you really need:

```
    {
        "key": "ctrl+x g",
        "command": "magit.status"
    },
    {
        "key": "alt+x g",
        "command": "-magit.status"
    }
```

for completeness you might also want:

```
    {
        "key": "ctrl+x ctrl+g",
        "command": "magit.dispatch"
    },
    {
        "key": "alt+x ctrl+g",
        "command": "-magit.dispatch"
    },
    {
        "key": "ctrl+x alt+g",
        "command": "magit.file-popup",
        "when": "activeEditor"
    },
    {
        "key": "alt+x alt+g",
        "command": "-magit.file-popup",
        "when": "activeEditor"
    }
```


Having it rely only on the native keyboard settings is a good place to be imo. And as you see there are only 1-3 cases you need to customize, depending on your need.
