### ISSUE TITLE
Partial hunk selection not possible

### ISSUE THREAD

**Issue by EdSplendor** [kahole/vscode-magit#226]
Selecting a line or multiple lines inside a hunk is not possible anymore. 
Always the whole hunk is automatically highlighted and therefore selected:

![hunk_bug](https://user-images.githubusercontent.com/1138016/195760241-a9da1ac6-1f4f-46c8-91e7-165c96a0f2ae.jpg)

**Comment by kahole** [comment]
I'm not sure I'm seeing a selection in the screenshot. You need to select at least one characters on a line to select a line. Looks like you might be using a Vim-emulator, depending on how visual mode in it works might not create a selection that other extensions can read. Try to have it result in a native vscode selection if you can.

**Comment by EdSplendor** [comment]
Yes, I'm using VSPaceCode, which uses a vim-emulator.
Thanks for the hint, I'll try to figure it out.
