### ISSUE TITLE
"key" has fingerprint "undefined" warning when using a hardware token that requires user presence

### ISSUE THREAD

**Issue by SeriousBug** [kahole/vscode-magit#227]
Hi! I'm using an `ed25519_sk` type ssh key, which is backed by a hardware token (Yubikey 5) that requires user presence to be verified before use. When pushing or pulling a repository with this key, I normally get a prompt like this:

![A message that says "Confirm user presence for key ED25519-SK"](https://user-images.githubusercontent.com/1008124/196591252-01676b7d-d7bc-438f-b068-02c6fa263371.png)

It seems like edamagit is confusing this for a warning about ssh fingerprints, and it shows me this warning:

![A warning message "key" has fingerprint "undefined"](https://user-images.githubusercontent.com/1008124/196591393-aceea064-e146-43f8-8e95-3f3316b57fa4.png)

The warning message displayed by edamagit seems to do nothing for me: as long as I press my hardware token the push or pull happens. But it would be nice if this warning was not unnecessarily displayed. Adding some sort of notice or prompt to remind users to touch the hardware token could be useful, but not strictly necessary because the hardware token has a light that will blink to remind users. The priority would be to not display the unnecessary warning.

**Comment by kahole** [comment]
This looks like a bug with the builtin VSCode git functionality that edamagit also relies on. You might want to report it over at the VSCode repo
