### ISSUE TITLE
what is magit-section-toggle in edamagit?

### ISSUE THREAD

**Issue by WingDust** [kahole/vscode-magit#229]
in magit ,have command `magit-section-toggle`
what is alternatives in edamagit?

**Comment by kahole** [comment]
`magit.toggle-fold`
By default `Tab` key triggers `magit.toggle-fold`. It's not available in the command prompt currently.
It's fairly easy to change that though. Might jump on that

**Comment by kahole** [comment]
Also, there was recently an issue reported on this command not working: https://github.com/kahole/edamagit/issues/228
Havent been able to reproduce this though ...
