### ISSUE TITLE
Toggle fold keybind (Tab) doesn't work with VSCodeVim extension enabled

### ISSUE THREAD

**Issue by kgreunke** [kahole/vscode-magit#239]
If you have the VSCodeVim extension enabled and try to toggle a fold in the status page nothing happens.  Debugging keybinds eventually lead me to this part of the when clause
```
vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/
```
I'm not sure what exactly the intent of that is, but if you change it to the following then the keybind does work (copied from a VSCodeVim keybind)
```
vim.mode != 'Insert'
```
I would imagine that removing it entirely would also work, but again, I'm not sure what the intent of the original clause is/was.

**Comment by kahole** [comment]
The intent was to not have commands be invoked when vim searching or writing vim commands while in the magit buffer. I think your suggestion has this problem. Of course for `TAB` this is likely not a big issue, it's worse for something like the letter `a`.
I'm not what caused it to not work for you, as far as I can tell the modes still have those names in VSCode-Vim.

**Comment by kgreunke** [comment]
I'm not sure either.  Is there something I can do to troubleshoot further?  I agree that my solution would not work in the case you mentioned, but I'm not sure what more I can do to help with this.

**Comment by kahole** [comment]
https://github.com/kahole/edamagit/pull/287
