### ISSUE TITLE
All magit commands fail with command not found

### ISSUE THREAD

**Issue by adamruzicka** [kahole/vscode-magit#252]
The extension doesn't seem to work at all for me right now. Running any magit commands from the command palette results in errors like these

![image](https://user-images.githubusercontent.com/7326770/235868560-8d9c37f9-bc23-44cb-8c5e-4834d8d433f3.png)

Keyboard shortcuts behave the same way, just the error appears as a popup in bottom right corner
![image](https://user-images.githubusercontent.com/7326770/235868731-d0015d49-1a48-4140-8fd0-12fc42cb5758.png)

edamagit version v0.6.40
vscode version 1.73.1

**Comment by kahole** [comment]
Are you able to / do you want to upgrade VSCode and see if that works? 1.73.1 is a bit old, and I remember there might have been some breaking changes to edamagit

**Comment by adamruzicka** [comment]
Oh, it works well with 1.77.3. My bad, sorry about the noise and thank you for getting back to me so swiftly
