### ISSUE TITLE
Support `.git` folder outside of the VS Code workspace

### ISSUE THREAD

**Issue by matklad** [kahole/vscode-magit#253]
This is the opposite of https://github.com/kahole/edamagit/issues/184: I have a git monorepo with many projects in subfolders, and I open individual folders in `code. When I invoke `magit status`, it suggests me to initialize a new repo in the current folder, rather than opening an existing one in the ancestor.

**Comment by matklad** [comment]
Ok, figured that out. This is controlled on the VS Code side, the following setting does the trick:

```json
{
  "git.openRepositoryInParentFolders": "always",
}
```

**Comment by kahole** [comment]
Great! Yeah, edamagit relies on a lot of VSCode's git functionality. So, sometimes config of vscode-git can be helpful 👍🏻
