### ISSUE TITLE
None of the commands work

### ISSUE THREAD

**Issue by jariji** [kahole/vscode-magit#254]
For example, the magit status command says "Command 'magit.status' not found".

Using the menu
![image](https://github.com/kahole/edamagit/assets/96840304/2ffc40dc-cdb4-4914-b658-0489f8602c19)

Using the keyboard shortcut 
![image](https://github.com/kahole/edamagit/assets/96840304/a4e346ea-b913-4b55-8897-7fad6165daf8)

edmagit v0.6.40
vscode 1.73.1 6261075646f055b99068d3688932416f2346dd3b x64
Linux (NixOS 22.11)

**Comment by kahole** [comment]
https://github.com/kahole/edamagit/issues/252

**Comment by jariji** [comment]
Thanks, sorry I missed that.
