### ISSUE TITLE
magit status not work

### ISSUE THREAD

**Issue by jidibinlin** [kahole/vscode-magit#261]
I got this log when in Extension host log
![image](https://github.com/kahole/edamagit/assets/38578679/81f22dff-46b4-41d6-8081-7d8c1d3edc8a)

**Comment by jidibinlin** [comment]
I`m woking on windows

**Comment by jsb05** [comment]
I had the same error. It's not Edamagit problem.  On Windows, if you installed git via scoop, VS code isn't able to find your git executable. Either edit the git-path variable in File -> Preferences -> Git -> settings.json or install Git for Windows natively.
