### ISSUE TITLE
Dyanmic help page when using vscodevim and vspacecode showing old bindings

### ISSUE THREAD

**Issue by m3dwards** [kahole/vscode-magit#266]
Absolutely love the project, magit was one of my favourite packages on emacs.

I'm using vscodevim and vspacecode which automatically installs the vim friendly keybindings for edamagit and those keybindings are working however when I press `?` I get the original keybindings listed:

I removed comments from my keybindings.json just incase those were tripping up the dynamic help but it didn't appear to help.

<img width="531" alt="Screenshot 2023-07-13 at 18 41 44" src="https://github.com/kahole/edamagit/assets/1204616/c941006d-3e27-4178-81be-b59100c500cd">

**Comment by m3dwards** [comment]
I've simplified my keybindings.json down to just one change to test:

```
[
	{
		"key": "x",
		"command": "magit.discard-at-point",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	},
	{
		"key": "k",
		"command": "-magit.discard-at-point"
	}
]
```

And confirmed that VSCode has picked up that change:
<img width="1219" alt="Screenshot 2023-07-13 at 18 47 59" src="https://github.com/kahole/edamagit/assets/1204616/dff2ddfa-25fb-4dd4-ab97-8c3023365194">

But still it shows discard as K on the help screen

**Comment by kahole** [comment]
Seems like the log path for extensions has changed, so the resolution of `keybindings.json` became wrong.

I've pushed and released a simple fix for this now so it should start working in `v0.6.45`.

As for preventing similar regressions in the future, I don't know if there's a better way to reliably locate `keybindings.json`. Open for suggestions

**Comment by m3dwards** [comment]
Brilliant thanks!
