### ISSUE TITLE
Keybindings for `TAB` broken

### ISSUE THREAD

**Issue by ralexstokes** [kahole/vscode-magit#274]
The keybinding for `TAB` recently broke for me, I'm assuming due to some underlying change in VSCode (or possibly the Vim extension?).

After a little debugging, I found changing the editor focus scoping fixes the issue:

Change: edit keybinding to use `editorTextFocus` in lieu of `editorFocus`.

After the change my `keybindings.json` looks like:

```json
// other settings elided...
{
    "key": "tab",
    "command": "extension.vim_tab",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert' && editorLangId != 'magit'"
  },
  {
    "key": "tab",
    "command": "-extension.vim_tab",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'"
  },
```

I'm opening this issue in case anyone else has the problem and is looking for a solution.

**Comment by m3dwards** [comment]
I had the same. Many thanks!

**Comment by lucasnad27** [comment]
Just to confirm, another report here. I thought I was going crazy trying to diff an unstaged file with TAB 😂

Thank you for the temp fix @ralexstokes !! Worked like a charm.

**Comment by robertfw** [comment]
Just ran into this as well. Thanks for the fix!

**Comment by alexrenz** [comment]
oh my god, you are a life saver! thank you so much ❤️

**Comment by davezuch** [comment]
Just ran into this too, thanks for the solution!

**Comment by hakalyanpur** [comment]
I am running into this too. Do all of you have vim bindings? I do not have vim bindings.And the above fix does not work for me @ralexstokes

**Comment by kahole** [comment]
What version of vscode are yall running?

**Comment by derkling** [comment]
I'm running `1.78.0` and had the same issue.

Fixed by the change proposed by @ralexstokes, thanks!

**Comment by m3dwards** [comment]
@nimbletactician I'm running vim bindings and have VSpaceCode installed.

**Comment by m3dwards** [comment]
> What version of vscode are yall running?

1.81.1

**Comment by hakalyanpur** [comment]
@kahole Version: 1.82.1

**Comment by hakalyanpur** [comment]
@derkling : Would you happen to have vim bindings too?

**Comment by hakalyanpur** [comment]
Thanks for responding @maxwedwards. I have tried a bunch of settings but still no luck. I do use IntelliJ Keybindings; not sure if that has a bearing.

**Comment by ralexstokes** [comment]
> have VSpaceCode installed.

I'm running this as well, and on `1.82.1` vscode version

**Comment by hakalyanpur** [comment]
Curious about what possible setting needs to be changed for someone like myself running neither of the bindings. 

To be precise: The tab folding feature on the Unstaged Changes line is working i.e. when I hit tab on the Unstaged Changes line, it does show/hide the underlying file. However, when I hit the tab on the file line to see the diff, it does not work.

Unstaged changes (3)
modified   test/automation/utils.go

@ralexstokes @kahole @maxwedwards

**Comment by m3dwards** [comment]
I don't know @nimbletactician

I would start by looking at what TAB is currently bound to in your keybindings.

**Comment by jlevers** [comment]
@nimbletactician I'm running into this issue too. Can't find any obviously overlapping keybindings. I'll update here if I find a solution.

**Comment by shapel** [comment]
Thank you, @ralexstokes, so much! ❤️

**Comment by jordangarrison** [comment]
Thank you @ralexstokes, this is great

**Comment by kahole** [comment]
https://github.com/kahole/edamagit/pull/287

**Comment by kahole** [comment]
Separate issue for tab folding problems beyond vim keybindings: https://github.com/kahole/edamagit/issues/228

**Comment by gerrywastaken** [comment]
@kahole
For what it is worth, the change [above](https://github.com/kahole/edamagit/issues/274#issue-1890874856) didn't fix this issue for me (using windsurf - vs fork with vim emulation) and I still need to use the keybinding mentioned in the first comment.

I also needed the following before `k` to move up would start working
```json
    {
        "key": "k",
        "command": "extension.vim_up",
        "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'"
    },
    {
        "key": "k",
        "command": "-extension.vim_up",
        "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'"
    }
```
