### ISSUE TITLE
Persistent "Running git stash list..." message in status bar

### ISSUE THREAD

**Issue by tdksk** [kahole/vscode-magit#279]
I've noticed a persistent message "Running git stash list..." appearing in the status bar whenever a file is open in the editor, following the changes made in https://github.com/kahole/edamagit/pull/275 .

The change seems beneficial, but in my environment, the message continues to display. I am not sure whether the content of the message is accurate, but its continuous display seems odd. I am unsure if this is a bug, but I decided to raise this issue.

![image](https://github.com/kahole/edamagit/assets/2177378/00f45863-8109-434d-8d29-e39054751ac3)

**Comment by kahole** [comment]
Thanks for reporting. There was a missing `dispose()`. Fix released in v0.6.47
