### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by dufferzafar** [kahole/vscode-magit#3]
Installed the extension and nothing works.

I keep getting `command 'magit.status' not found`error. And similar ones for other commands as well.

**Comment by kahole** [comment]
What version?
Platform?

**Comment by srijan** [comment]
I'm getting the same error.

Environment: Ubuntu on WSL2 on Windows 10, with vscode using Remote-WSL connection.

Debug console:
```
notificationsAlerts.ts:38 Error: command 'magit.status' not found
    at u._tryExecuteCommand (commandService.ts:80)
    at commandService.ts:73
    at async t (commandsHandler.ts:325)
onDidNotificationChange @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:582
addNotification @ notifications.ts:171
error @ notificationService.ts:57
onError @ commandsHandler.ts:356
t @ commandsHandler.ts:334
async function (async)
t @ commandsHandler.ts:325
(anonymous) @ commandsHandler.ts:345
setTimeout (async)
runAction @ commandsHandler.ts:345
run @ commandsHandler.ts:303
run @ quickOpenModel.ts:576
elementSelected @ quickOpenWidget.ts:587
(anonymous) @ quickOpenWidget.ts:251
```

**Comment by kahole** [comment]
Try completely removing the extension, and installing again. This seems related to the file name case sensitive issue fixed in version 0.0.5

**Comment by srijan** [comment]
Tried Uninstall + Restart + Install + Restart: same error.

Is there some other way to "completely remove" the extension?

**Comment by kahole** [comment]
```
To clear the VS Code extension cache folder:

    Open the folder in C:\Users\<username>\. vscode\extensions.
    Delete all files in the folder.
```

**Comment by srijan** [comment]
> ```
> To clear the VS Code extension cache folder:
> 
>     Delete the folder in ~/.vscode/extensions/kahole.magit-0.0.5
> ```
> 
> Just delete magit extension folder in there, and restart and re-install. Should be good then, I think.

Tried this. Still same error.

Another data point: I've clean-installed magit both in WSL environment and in Windows environment.
It works when I open a project in the windows environment.
But, it gives the above mentioned error when I try inside the WSL environment.

**Comment by srijan** [comment]
If I manually change these 4 lines to use `HunkView` instead of `hunkView`, then it works:

```
./out/views/changes/changeView.js:const hunkView_1 = require("./HunkView");
./out/commands/visitAtPointCommands.js:const hunkView_1 = require("../views/changes/HunkView");
./out/commands/stagingCommands.js:const hunkView_1 = require("../views/changes/HunkView");
./out/commands/discardCommands.js:const hunkView_1 = require("../views/changes/HunkView");
```

Maybe because WSL is linux, which is case sensitive?

**Comment by kahole** [comment]
Yep, did a clean build on my side, trying to get rid of every last capital H. grepped for them and dint find any
lets see how it goes, v.0.0.6
