### ISSUE TITLE
[BUG][Cursor] COMMIT_EDITOR opens up as a new Cursor window in 0.6.64

### ISSUE THREAD

**Issue by cad** [kahole/vscode-magit#325]
When I hit c c, the existing Cursor window is replaced with a new one with only the commit message is opened up. I use multiple-windows of Cursor. This is started happening in 0.6.64 and it doesn't happen on 0.6.62

**Comment by The-Compiler** [comment]
Are you using [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)? If so, I'm seeing the same and opened #327 with more details.

**Comment by cad** [comment]
@The-Compiler Yeah, that seems to be the case. Closing this in favor of #327.
