### ISSUE TITLE
Not compatible with VS Code 1.41

### ISSUE THREAD

**Issue by ishovkun** [kahole/vscode-magit#4]
Hi,
I am trying to install your extension from VS Code extension marketplace.
I am getting an error saying that magit is not compatible with my version of the editor (1.41).
I am using the editor version from the Manjaro Linux repositories.

Please let know know should I provide more information. I am not really familiar with VS code but tinker with it sometimes to see whether it could replace emacs.

**Comment by kahole** [comment]
Sadly there was a bit of an issue(1) with VSCode version 1.42.0, breaking the extension.
So I decided to set the minimum required version at 1.42.1. I'm not sure if this is the best way of handling it.

However the extension should work fine with version 1.41.x. You can build it from source and adjust the min vscode engine parameter in package.json.

(1) https://github.com/microsoft/vscode/issues/90229

**Comment by ishovkun** [comment]
I updated my system this morning and got 1.42 installed. I confirm that it works.
