### ISSUE TITLE
Enter on diff opens file

### ISSUE THREAD

**Issue by Silex** [kahole/vscode-magit#83]
Hello,

Awesome! Suggestion: when displaying a diff, allow the user to press enter to jump to that file.

Bonus point if you do it like in magit:
- Enter just shows the file contents from the commit (old)
- Control-Enter opens the current file.

**Comment by kahole** [comment]
A rework of the commit view is planned, making it more interactive and similar to the one in magit emacs. 👍

**Comment by Silex** [comment]
I'm currently deciding wether I switch to vscode (I'm currently using Emacs). If I do I'll probably contribute :wink:

**Comment by dandavison** [comment]
I agree that this is an important magit-parity feature to implement.

To expand on @Silex's point, by default magit has `enter` on a commit diff line bound to (`magit-diff-visit-file`), which takes you to a non-editable buffer displaying the historical state of the file. But if the diff is showing uncommitted changes (staged or unstaged) `magit-diff-visit-file` takes you to an editable view of the current file.

In contrast `ctrl+enter` is bound to `magit-diff-visit-worktree-file`, which always takes you to the line in an (editable) editor view displaying the current file.

I would also like to have both behaviors available. In fact, personally, a common work flow for me is:

1. `l l` (view git log)
2. `Enter` (view latest commit to remind me of what I was doing)
3. `Enter` (go to a specific line in a file touched by the latest commit to start working)

So, in Emacs magit I switch the bindings:

```emacs-lisp
(use-package magit
  :bind (:map magit-diff-mode-map
         ([return] . magit-diff-visit-worktree-file)
         ([control return] . magit-diff-visit-file)))
```

But of course one could have uncommitted changes to the file in which case you will be taken to a view showing different file state from what was in the diff.
