### ISSUE TITLE
Checking out a branch puts me on a detached commit from that branch

### ISSUE THREAD

**Issue by beem812** [kahole/vscode-magit#86]
Hi, loving the extension so far but something weird has been happening for me. 

Occasionally when I checkout a branch, by selecting it from b -> b  or b -> l menu, I end up with a detached head on the latest commit of that branch. I'm not really sure what causes it and repeated switching to the branch in question does not always land me in the unwanted state but will instead put me where I expect to be. Is there some command I might be unintentionally entering that does this? Unfortunately all I do to reproduce it is go about my business switching branches and occasionally see that the git status says the Head is a commit hash and no the branch name/ commit message.

**Comment by kahole** [comment]
Could you post the contents of the edamagit git log the next time it happens?
You bring it up using `$` from edamagit.

Also, what platform, git version, and vscode version do you use? :)

**Comment by beem812** [comment]
Platform: mac
git version: 2.15.0
vscode version: 1.50

magit log:

git checkout origin/\<a branch name\>
Note: checking out 'origin/\<a branch name\>'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d4d32d0... package-lock you are a jerk




it wouldn't have anything to do with checking out an origin branch would it?

**Comment by kahole** [comment]
Yes, it's because you're checking out a remote branch. This is how git works also.

You should use `b->c` and choose the remote branc. It will pre-fill the branch name and create a local branch for you.

**Comment by beem812** [comment]
excellent, thanks!

**Comment by adisidev** [comment]
I just want to say thank you: this issue was really useful to have here!
