### ISSUE TITLE
Default keybindings incompatible with Emacs

### ISSUE THREAD

**Issue by jedbrown** [kahole/vscode-magit#87]
https://github.com/tuttieee/vscode-emacs-mcx seems to be the most popular Emacs keybinding extension. It makes sense that folks moving from Emacs would want both the keybindings and Magit-like features, thus use these two packages together. And yet the default bindings (still displayed in the command window :point_down:) are unavailable because `Alt+X` is `Show All Commands` (similar to Emacs).
![image](https://user-images.githubusercontent.com/3303/96793725-20cbbd00-13ba-11eb-87fe-0b94a4e24304.png)

**Comment by kahole** [comment]
Based on the issue-history of this repo, I would guess that the Vim-keybindings are more popular than the Emacs keybindings, in conjunction with edamagit.
This is also supported by the huge disparity in number-of-downloads between the Vim and Emacs keybinding extensions.

I also wouldn't really know what to change it to.
I suggest you configure it in your vscode keybindings.
