### ISSUE TITLE
Comparison with GitSavvy

### ISSUE THREAD

**Issue by franciscolourenco** [kahole/vscode-magit#88]
I miss GitSavvy in VSCode, and was wondering how Edamagit compares in terms of features and usability.

https://github.com/timbrel/GitSavvy#documentation

Thanks!

**Comment by kahole** [comment]
They look to be quite similar. Being text-based UIs for Git integrated with editors.
A lot of common and similar functionality as well.
I'm guessing `GitSavvy` is inspired by the same program as `edamagit`, namely `Magit` (emacs magit https://magit.vc/).

Currently there is very little documentation or guides for edamagit, but it tries to a great degree to emulate magit operations.

Once in the edamagit status view, you may press `?` to show the possible actions and their keys.
