### ISSUE TITLE
Support for "fixup" commits

### ISSUE THREAD

**Issue by zachdaniel** [kahole/vscode-magit#9]
In magit I can say `c f` to do a fixup commit, and then choose a commit to fixup. Would love to see support for that in vscode magit as well.

**Comment by zachdaniel** [comment]
Looks like it is commented out here, probably because its not set up to allow you to choose from a list of commits, right?
https://github.com/kahole/vscode-magit/blob/f6751982e8857cc05f6df48b60677846bed09485/src/commands/commitCommands.ts#L18

**Comment by kahole** [comment]
Thank you for your feedback :)
Magit just has so many big and small features, I've so far focused on the ones I myself use most frequently. So great to have some input.

The fixup selection view in Magit looks just like the log view, from which there already is visit-at-point functionality to explore commits.
The logging view and commands themselves needs improvements too, of course.
This might be a good place to start.
