### ISSUE TITLE
Select git repository to use when in a multi-root workspace

### ISSUE THREAD

**Issue by roblabla** [kahole/vscode-magit#90]
VSCode has the ability to create multi-root workspaces - a workspace containing multiple folders. See [the documentation](https://code.visualstudio.com/docs/editor/multi-root-workspaces). Each folder may have its own git, and vscode's native SCM handling deals with that properly.

Edamagit, on the other hand, will pick a seemingly random repository to work with. I suppose it should at least ask the user which folder it wants to run edamagit in. For instance, when creating a terminal, VSCode shows this prompt: 
![image](https://user-images.githubusercontent.com/1069318/100078422-cce24700-2e43-11eb-8533-0908f2f59748.png). It could also try to detect the git repo we want to open based on the current file?

To reproduce:

- Create an empty vscode window
- File -> Add Folder to Workspace, select two directories, each with a git repository
- Open edamagit status.

**Comment by kahole** [comment]
It should detect repo based on current file. Is this not working?

There is a call to `vscode.workspace.workspaceFolders // from docs: where first entry is root` in the discovery process, this might be the randomness you're experiencing as I'm not sure what it returns in a multi-root environment. (probably just the first by some happenstance).
However, this is only after it fails to detect based on currently open file.

If it's possible to detect multi-root, the workspace match-step should be skipped. As the next step is in fact already a prompt asking user to choose repo manually from a list.

**Comment by roblabla** [comment]
> It should detect repo based on current file. Is this not working?

Hmm, I'll need to do further testing. It seems to fail on some files, there's probably a common reason to the cases where it doesn't work, but I haven't been able to precisely figure out what that is yet. I'll get back to this when I have a solid idea of what's up.

> There is a call to vscode.workspace.workspaceFolders // from docs: where first entry is root in the discovery process, this might be the randomness you're experiencing as I'm not sure what it returns in a multi-root environment. (probably just the first by some happenstance).

Yeah, that's probably it. FWIW in the minimal reproducer I used before submitting, I didn't have any file opened. In this situation, a prompt should show up for sure.

> If it's possible to detect multi-root, the workspace match-step should be skipped. 

Multi-root can be trivially detected by checking if `vscode.workspace.workspaceFolders.length > 1`.

**Comment by kahole** [comment]
I found a couple of subtle issues in the discovery procedure (It's due for a rewrite...), and patched them up.
Let me know if you are able to verify the fix :)
