### ISSUE TITLE
How does cherry pick work?

### ISSUE THREAD

**Issue by danielo515** [kahole/vscode-magit#91]
Hello,
I wanted to cherry pick an specific commit but what I get is the command palette to choose a branch. I'm supposed to write the commit id there or how?

**Comment by kahole** [comment]
Yes, the branches are just there as suggestions.
You can enter a short or long commit-hash, or any ref, and press enter to cherry-pick it.


I realize this is likely not clear for new users. Or users not familiar with Helm+Magit in Emacs.
Thank you for the feedback :)

**Comment by danielo515** [comment]
Hey, thanks for answering. Is it impossible to, additionally to branches, show also commits with their commit message?
Something that is not clear either is what picking a branch means: will it cherry pick the latest commit (I think it does)? Or will it pick several ones?

**Comment by kahole** [comment]
All commits (newest first), or just the ones for the currently checked out branch? I see your point of it being nice to suggest recent commits to be picked. I will consider adding something like that.

> Something that is not clear either is what picking a branch means: will it cherry pick the latest commit (I think it does)? Or will it pick several ones?

Branches, tags, etc, are just pointers to specific commits.
The input is free form and accepts any string. You should treat it as if entering the `<commit>` part for the git command, it works the same. Meaning you can refer to hashes, relative commits e.g. origin/branchA~1, etc.
So, yes, only the last commit on a brqnch will be picked when you select a branch.
```
git cherry-pick [--edit] [-n] [-m parent-number] [-s] [-x] [--ff]
		  [-S[<keyid>]] <commit>
```
(https://git-scm.com/docs/git-cherry-pick)

**Comment by danielo515** [comment]
Oh, I didn't knew cheery-pick was able to accept a branch as argument. This is my fault totally.
Thanks for your answers and patience.
