### ISSUE TITLE
Publish to Open VSX registry

### ISSUE THREAD

**Issue by marcoieni** [kahole/vscode-magit#93]
Hi! I am one of the maintainers of [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode), which bundles the edamagit extension.

We would like to publish VSpaceCode to https://open-vsx.org/ in order to make it easier for people who use IDEs like VSCodium, Theia, etc. to install it. However, we won't be able to do it until all the extensions we bundle are published on open-vsx, too.

We already successfully published one of our bundled extension, [vscode-which-key](https://github.com/VSpaceCode/vscode-which-key) to open-vsx using a [GitHub Action](https://github.com/VSpaceCode/vscode-which-key/blob/master/.github/workflows/deploy.yml). On every tag, the extension is deployed automatically to both Visual Studio Marketplace and Open VSX.

Publishing extension to open-vsx is very simple and you can follow their [official instruction](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension).
Would you please consider this? Thanks!

**Comment by kahole** [comment]
That was simple enough. Let me know if there is anything out of order:
https://open-vsx.org/extension/kahole/magit

Thanks for the "github action" suggestion. Will use it going forward.

**Comment by marcoieni** [comment]
If I go to the link you provided I get this message:

![image](https://user-images.githubusercontent.com/11428655/101988096-01556000-3c98-11eb-98b8-facbfec51d7e.png)

I don't think it's a good thing 😅

**Comment by kahole** [comment]
https://github.com/EclipseFdn/open-vsx.org/issues/260
