### ISSUE TITLE
Asked to choose a repository when trying to stage all changes

### ISSUE THREAD

**Issue by ellamental** [kahole/vscode-magit#96]
I installed this extension about 10 minutes ago, so I wouldn't be surprised if there's just something I'm missing...

To reproduce:

1) Open 2 files in separate repos
2) Make some changes to one
3) Run `magit.status`
4) Move point/cursor to the "Unstaged Changes" line
5) Press `s` to stage all
6) "Choose a repository" dialog pops up

I'd think the repository should be pretty obvious. 😄

<img width="1039" alt="Screen Shot 2020-12-19 at 2 31 45 AM" src="https://user-images.githubusercontent.com/385989/102685030-26b80180-41a3-11eb-9abb-ba7f75618ee9.png">

As you can see from the screenshot, this also happens when there's just 1 unstaged file (even though staging the file individually works without the "choose a repo" dialog).

edamagit version: 0.6.0
VSCode version: 1.52.1
OS: Mac 10.15.7

**Comment by kahole** [comment]
Thanks for reporting. This was leftover usage of built-in vscode commands for staging and unstaging "all", as to speed up development.
I've now replaced them with custom commands. Will be included in the next release, after some more testing.

**Comment by kahole** [comment]
v0.6.1 published

**Comment by ellamental** [comment]
I upgraded and confirmed this is fixed as well.  Thanks!
