### ISSUE TITLE
Cannot commit or abort if commit message opens in new window

### ISSUE THREAD

**Issue by ellamental** [kahole/vscode-magit#97]
To reproduce:
1) Add `"window.openFilesInNewWindow": "on",` to your `settings.json`.
2) Restart
3) Stage some changes, then `c c` to commit
4) A new window should open with the `COMMIT_EDITMSG` buffer
5) Write a commit message
6) `C-c C-c` (error `command magit.save-and-close-editor not found`)
7) `C-C C-k` (error `command magit.clear-and-abort-editor not found`)

<img width="1024" alt="Screen Shot 2020-12-19 at 2 49 23 AM" src="https://user-images.githubusercontent.com/385989/102685597-87e1d400-41a7-11eb-9325-d444f52f2d3a.png">

Everything seems to work fine when I set: `"window.openFilesInNewWindow": "off",`.

edamagit version: 0.6.0
VSCode version: 1.52.1
OS: Mac 10.15.7

**Comment by kahole** [comment]
Fixed it in the above commit. It will be included in the next release.

Although, `C-c C-c` and `k` are just macros for
`saving the file and closing the editor`
and
`clearing the editor, saving the file, and closing the editor`

So just doing those things manually will work, just like if your GIT_EDITOR was vscode.

**Comment by kahole** [comment]
v0.6.1 published

**Comment by ellamental** [comment]
I upgraded and confirmed this is fixed.  Thanks!  And thanks for the work you've done on this package!  I'm trying to switch to vscode (mostly for the "dev containers" stuff) after many years of Emacs, and having a solid substitute for Magit is a huge help!  I'll definitely be buying you a few coffees.  😄
