### ISSUE TITLE
magit.status window doesn't appear

### ISSUE THREAD

**Issue by jtrakk** [kahole/vscode-magit#98]
It used to work but now none of the magit commands seem to do anything. For example, the magit status command should open a window but it doesn't. Here is the log from `Show logs > Extension Host`:

```
[exthost] [info] ExtensionService#_doActivateExtension kahole.magit {"startup":false,"extensionId":{"value":"kahole.magit","_lower":"kahole.magit"},"activationEvent":"onCommand:magit.status"}
[exthost] [info] ExtensionService#loadCommonJSModule file:///home/user/.vscode/extensions/kahole.magit-0.6.1/dist/extension
```

---
Magit 0.6.1
VSCode  code --version 1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64
Linux beta 5.9.12 #1-NixOS SMP Wed Dec 2 07:52:03 UTC 2020 x86_64 GNU/Linux

**Comment by kahole** [comment]
Sorry to hear. I've not been able to reproduce this yet.
Try restarting vscode, as the extension upgrade might have gone wrong. If not try upgrading to the latest vscode version: 1.52.1
Let me know whether or not it works out

**Comment by jtrakk** [comment]
Thanks. It seems to be working now. I'm not sure if it was the new version or what exactly fixed it.
